""" Defines colors used in the ui and led indicator """
class Color():
    LED_OFF = "#000000"
    NO_SIGNAL = "#ff0000"
    BAD_SIGNAL = "#f67b29"
    VERY_WEAK_SIGNAL = "#f3c83b"
    WEAK_SIGNAL = "#faf62b"
    MEDIUM_SIGNAL = "#beeb42"
    GOOD_SIGNAL = "#4bc37d"
    VERY_GOOD_SIGNAL = "#38b8d2"
    EXCELLENT_SIGNAL = "#1cafe9"